return {
	BasicCrate = {
		Icon = "rbxassetid://74352048491243",
		Items = {
			BasicUnit = 100,
		},
		Cost = 10,
		CurrencyType = "Coins",
		Color = Color3.fromRGB(124, 255, 1),
	},

	AdvancedCrate = {
		Icon = "rbxassetid://74352048491243",
		Items = { BasicUnit = 100 },
		Cost = 50,
		CurrencyType = "Coins",
		Color = Color3.fromRGB(108, 0, 250),
	},

	ExclusiveCrate = {
		Icon = "rbxassetid://74352048491243",
		Items = { BasicUnit = 100 },
		Cost = 100,
		CurrencyType = "Coins",
		Color = Color3.fromRGB(255, 1, 1),
	},
}
